---
title: "R Notebook"
output:
  html_document:
    keep_md: yes
    self_contained: no
---
This is an exploration of the John Hopkins data.

```{r}
library(readr)
library(data.table)
library(ggplot2)
library(plotly)
library(directlabels)
library(dplyr)

```



```{r}

deaths<-data.table(read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"))

confirmed_cases<-data.table(read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"))
country_populations<-data.table(read.csv("population-figures-by-country-csv_csv.csv"))

```


```{r}
tidy_data <- function(confirmed_cases){
  confirmed_cases<-confirmed_cases[,1:(ncol(confirmed_cases))]
  transform_cols<-colnames(confirmed_cases)[5:ncol(confirmed_cases)]
  id_vars <- c("Country/Region","Province/State","Lat","Long")
  
  
  confirmed_cases_long <- melt(confirmed_cases,
                               id.vars=id_vars,
                               measure.vars = transform_cols,
                               variable.name = "case_date",
                               value.name = "Confirmed Cases"
                               )
  
  
  confirmed_cases_long[,SelectedRegion:=`Country/Region`]
  #confirmed_cases_long[`Country/Region`=="China",SelectedRegion:=paste0(`Province/State`," (China)")]
  
  
  confirmed_cases_long_bycountry <- confirmed_cases_long[,.(`Confirmed Cases`=sum(`Confirmed Cases`)),by=.(SelectedRegion,case_date)]
  
  pops_clean<-country_populations[,.(Country,Population2016=Year_2016)]
  pops_clean<-rbind(pops_clean,data.table("Country"="Taiwan*","Population2016"=23800000))
  population_renaming<-list(list("Brunei","Brunei Darussalam"),
                            list("Czechia","Czech Republic"),
                            list("Egypt","Egypt, Arab Rep."),
                            list("French Guiana","Guyana"),
                            list("Iran","Iran, Islamic Rep."),
                            list("Korea, South","Korea, Rep."),
                            list("North Macedonia","Macedonia, FYR"),
                            list("Russia","Russian Federation"),
                            list("Slovakia","Slovak Republic"),
                            list("US","United States"))
  for (poptuple in population_renaming){
    pops_clean[Country==poptuple[[2]],Country:=poptuple[[1]]]
  }
  
  
  confirmed_cases_long_bycountry<-
    merge(confirmed_cases_long_bycountry,
          pops_clean,
          by.x="SelectedRegion",
          by.y="Country",
          all.x=TRUE
          )
  
  confirmed_cases_long_bycountry$case_date<-as.Date(confirmed_cases_long_bycountry$case_date,format="%m/%d/%y")
  
       #make it easy to see the US & UK
     confirmed_cases_long_bycountry[SelectedRegion=="US",
                                    SelectedRegion:="United States",
                                    ]
     confirmed_cases_long_bycountry[SelectedRegion=="UK",
                                    SelectedRegion:="United Kingdom",
                                    ]
     
  return(confirmed_cases_long_bycountry)
}
confirmed_cases_long_bycountry <- tidy_data(confirmed_cases)
deaths_long_bycountry <- tidy_data(deaths)
colnames(deaths_long_bycountry)[3]<-"Deaths"
cases_and_deaths<-merge(confirmed_cases_long_bycountry,deaths_long_bycountry,all.x = TRUE,all.y=TRUE)
```

now get cases at a particular point in time.
```{r}

threshold<-1000
 
 #mark which days have reached the threshold
 cases_and_deaths[,IsAtOrPastThreshold:=(`Confirmed Cases`>=threshold)]
 
 #identify the first day for each country that has reached the threshold
 cases_and_deaths[,
                                DatePastThreshold:=min(.SD[IsAtOrPastThreshold==TRUE,case_date]),
                                by=SelectedRegion]
 
 cases_and_deaths[,DaysPastThreshold:=as.integer(case_date-DatePastThreshold)]
 
  
 
     
```
```{r}
ggplot(cases_and_deaths[DaysPastThreshold==0],aes(x = `Confirmed Cases`,y=Deaths,label=SelectedRegion))+geom_point()+geom_text(size=2,hjust = 0, nudge_x = 5)+
  coord_cartesian(xlim=c(1000,1300))
```


```{r}
ggplot(cases_and_deaths[DaysPastThreshold==0],aes(Deaths))+geom_histogram(binwidth = 2)+
  scale_y_continuous(breaks = c(0,2,4,6,8,10))+scale_x_continuous(breaks=seq(0,100,10))
```

```{r}
knitr::kable(cases_and_deaths[DaysPastThreshold==0,.(SelectedRegion,Deaths)] %>% .[,.(Regions=paste0(SelectedRegion,collapse=", ")),by=Deaths] %>% .[order(Deaths)],caption = "COVID-19 deaths in regions on their first day with at least 1000 confirmed cases")
```
```{r}
median(cases_and_deaths[DaysPastThreshold==0,.(Deaths)][[1]])
```

