---
title: "R Notebook"
output:
  html_document:
    keep_md: yes
    self_contained: no
---
This is an exploration of the John Hopkins data.

```{r}
library(readr)
library(data.table)
library(ggplot2)
library(plotly)
library(directlabels)
library(dplyr)

```



```{r}

confirmed_cases<-data.table(read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"))
country_populations<-data.table(read.csv("population-figures-by-country-csv_csv.csv"))

```

Let's get cases by country, to make this a bit easier.

```{r}
confirmed_cases<-confirmed_cases[,1:(ncol(confirmed_cases))]
transform_cols<-colnames(confirmed_cases)[5:ncol(confirmed_cases)]
id_vars <- c("Country/Region","Province/State","Lat","Long")


confirmed_cases_long <- melt(confirmed_cases,
                             id.vars=id_vars,
                             measure.vars = transform_cols,
                             variable.name = "case_date",
                             value.name = "Confirmed Cases"
                             )

confirmed_cases_long[,SelectedRegion:=`Country/Region`]
confirmed_cases_long[`Country/Region`=="China",SelectedRegion:=`Province/State`]

confirmed_cases_long_bycountry <- confirmed_cases_long[,.(`Confirmed Cases`=sum(`Confirmed Cases`)),by=.(SelectedRegion,case_date)]

pops_clean<-country_populations[,.(Country,Population2016=Year_2016)]
pops_clean<-rbind(pops_clean,data.table("Country"="Taiwan*","Population2016"=23800000))
population_renaming<-list(list("Brunei","Brunei Darussalam"),
                          list("Czechia","Czech Republic"),
                          list("Egypt","Egypt, Arab Rep."),
                          list("French Guiana","Guyana"),
                          list("Iran","Iran, Islamic Rep."),
                          list("Korea, South","Korea, Rep."),
                          list("North Macedonia","Macedonia, FYR"),
                          list("Russia","Russian Federation"),
                          list("Slovakia","Slovak Republic"),
                          list("US","United States"))
for (poptuple in population_renaming){
  pops_clean[Country==poptuple[[2]],Country:=poptuple[[1]]]
}


confirmed_cases_long_bycountry<-
  merge(confirmed_cases_long_bycountry,
        pops_clean,
        by.x="SelectedRegion",
        by.y="Country",
        all.x=TRUE
        )
#View(confirmed_cases_long_bycountry[,.(Pop=mean(Population2016)),by=SelectedRegion] %>% .[is.na(Pop)])
```

```{r}
confirmed_cases_long_bycountry$case_date<-as.Date(confirmed_cases_long_bycountry$case_date,format="%m/%d/%y")
ggplot(confirmed_cases_long_bycountry[SelectedRegion %in% c("New Zealand","Australia","Canada")],
       aes(x=case_date,y=`Confirmed Cases`,group=SelectedRegion,color=SelectedRegion))+
  geom_line() + 
  scale_x_date(limits=c(min(confirmed_cases_long_bycountry$case_date),max(confirmed_cases_long_bycountry$case_date)+8))+
  geom_dl(aes(label=SelectedRegion),method=list("last.qp",cex=1))
```


```{r}
threshold<-4
#mark which days have reached the threshold
confirmed_cases_long_bycountry[,IsAtOrPastThreshold:=(`Confirmed Cases`>=threshold)]

#identify the first day for each country that has reached the threshold
confirmed_cases_long_bycountry[,
                               DatePastThreshold:=min(.SD[IsAtOrPastThreshold==TRUE,case_date]),
                               by=SelectedRegion]

#then calculate the case_date relative to the threshold
confirmed_cases_long_bycountry[,DaysPastThreshold:=as.integer(case_date-DatePastThreshold)]


confirmed_cases_long_bycountry$case_date<-as.Date(confirmed_cases_long_bycountry$case_date,format="%m/%d/%y")

     #make it easy to see the US & UK
     confirmed_cases_long_bycountry[SelectedRegion=="US",
                                    SelectedRegion:="United States",
                                    ]
     confirmed_cases_long_bycountry[SelectedRegion=="UK",
                                    SelectedRegion:="United Kingdom",
                                    ]
```


```{r}

    threshold<-50
     
     #mark which days have reached the threshold
     confirmed_cases_long_bycountry[,IsAtOrPastThreshold:=(`Confirmed Cases`>=threshold)]
     
     #identify the first day for each country that has reached the threshold
     confirmed_cases_long_bycountry[,
                                    DatePastThreshold:=min(.SD[IsAtOrPastThreshold==TRUE,case_date]),
                                    by=SelectedRegion]
     
     #then calculate the date relative to the threshold
     confirmed_cases_long_bycountry[,DaysPastThreshold:=as.integer(case_date-DatePastThreshold)]
     
      confirmed_graph<-confirmed_cases_long_bycountry
     #Remove China if it was above the threshold on the first day. we don't do this to any other countries
     #but China is further along than all others.
     if(threshold<min(confirmed_graph[SelectedRegion=="China",`Confirmed Cases`])){
       confirmed_graph <- 
         confirmed_graph[SelectedRegion!="China"]
     }

     
     
     case_limit<-40
     days_limit <- 21

     #now we want a list of the lines
     #with an x axis point either at the end of the graph,
     #or at the end of the line, whichever is first,     
     country_labels<-confirmed_graph[,
                                    .(intercept_day=min(days_limit,max(DaysPastThreshold))),
                                    by=SelectedRegion] %>% .[!is.na(intercept_day)] %>%
       #and then at that x-axis point, we want the y-axis point.  
       merge(confirmed_graph[,.(SelectedRegion,DaysPastThreshold,`Confirmed Cases`,DatePastThreshold)],
                           by.x=c("SelectedRegion","intercept_day"),
                           by.y=c("SelectedRegion","DaysPastThreshold"),
             all.x=TRUE,all.y=FALSE)
 
     x_breaks  <- seq(-7,days_limit,7)
     x_labels <- c(paste(abs(x_breaks[1]),"Days Before"),
                   x_breaks[2:(length(x_breaks)-1)],
                   paste(x_breaks[length(x_breaks)],"Days After"))
     myplot<-ggplot(confirmed_graph
            # [SelectedRegion %in%
            #                                  c("New Zealand","Australia",
            #                                    "Canada","Denmark","Singapore",
            #                                    "Hong Kong","US")]
            ,
            aes(x=DaysPastThreshold,y=`Confirmed Cases`,
                group=SelectedRegion,color=DatePastThreshold))+
       geom_line(size=1,alpha=0.3)+
       #geom_point(alpha=0.5)+
       scale_x_continuous(limits=c(-7,days_limit),
                          breaks=x_breaks,
                          labels = x_labels)+
       coord_cartesian(xlim=c(-7,days_limit+3))+
       scale_y_continuous(trans = "log10",
                          breaks = c(1,2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000),
                          minor_breaks=NULL,
                          labels = scales::comma,
                          sec.axis = dup_axis())+
       geom_vline(xintercept = 0,linetype="dashed")+
       #geom_hline(yintercept = threshold,,linetype="dashed")+
       labs(title=paste0("Growth in cases by day from the ",threshold," case mark, by country"),
            x=paste0("Days past first day with ",threshold," cases"),
            y="Total confirmed cases",
            color="Date Country Reached Threshold")+
       theme(legend.position = "none")+
       geom_text(data=country_labels,
                 aes(x=intercept_day,y=`Confirmed Cases`,label=SelectedRegion),
                 hjust=0,size=2,fontface="bold")

  
  myplot
```


Can we plot the number of new cases by day?


```{r}
confirmed_cases_long_bycountry[order(case_date),
                               `New Cases`:=(`Confirmed Cases`-shift(`Confirmed Cases`)),
                               SelectedRegion]
  
#moving average over 7 days; figure is dated on the last day of the average window.
confirmed_cases_long_bycountry[order(case_date),
                               NewCasesMA:=shift(zoo::rollapply(`New Cases`,7,mean),6),
                               SelectedRegion]

new_cases<-confirmed_cases_long_bycountry[!is.na(NewCasesMA)]

if(threshold<min(new_cases[SelectedRegion=="Mainland China",`Confirmed Cases`])){
       new_cases <- 
         new_cases[SelectedRegion!="Mainland China"]
     }

case_limit<-40
days_limit <- 21

#now we want a list of the lines
#with an x axis point either at the end of the graph,
#or at the end of the line, whichever is first,     
country_labels<-new_cases[,
                              .(intercept_day=min(days_limit,max(DaysPastThreshold))),
                              by=SelectedRegion] %>% .[!is.na(intercept_day)] %>%
 #and then at that x-axis point, we want the y-axis point.  
 merge(new_cases[,.(SelectedRegion,DaysPastThreshold,NewCasesMA,DatePastThreshold)],
                     by.x=c("SelectedRegion","intercept_day"),
                     by.y=c("SelectedRegion","DaysPastThreshold"),
       all.x=TRUE,all.y=FALSE)

x_breaks  <- seq(-7,days_limit,7)
x_labels <- c(paste(abs(x_breaks[1]),"Days Before"),
             x_breaks[2:(length(x_breaks)-1)],
             paste(x_breaks[length(x_breaks)],"Days After"))
myplot<-ggplot(new_cases
      ,
      aes(x=DaysPastThreshold,y=NewCasesMA,
          group=SelectedRegion,color=DatePastThreshold))+
 geom_line(size=1,alpha=0.3)+
 #geom_point(alpha=0.5)+
 scale_x_continuous(limits=c(-7,days_limit),
                    breaks=x_breaks,
                    labels = x_labels,
                    minor_breaks=NULL)+
 coord_cartesian(xlim=c(-7,days_limit+3),ylim=c(1,max(new_cases$NewCasesMA)))+
 scale_y_continuous(trans = "log10",
                    breaks = c(1,2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000),
                    minor_breaks=NULL,
                    labels = scales::comma,
                    sec.axis = dup_axis())+
 geom_vline(xintercept = 0,linetype="dashed")+
 #geom_hline(yintercept = threshold,,linetype="dashed")+
 labs(title=paste0("Growth in new cases by day from the ",threshold," case mark, by country"),
      x=paste0("Days past first day with ",threshold," cases"),
      y="New Cases (7 day rolling average)",
      color="Date Country Reached Threshold")+
 theme(legend.position = "none")+
 geom_text(data=country_labels,
           aes(x=intercept_day,y=NewCasesMA,label=SelectedRegion),
           hjust=0,size=2,fontface="bold")

  
  myplot
```


```{r}
confirmed_cases_long_bycountry[order(case_date),
                               `New Cases`:=(`Confirmed Cases`-shift(`Confirmed Cases`)),
                               SelectedRegion]
  
#moving average over 7 days; figure is dated on the last day of the average window.
confirmed_cases_long_bycountry[order(case_date),
                               #NewCasesMA:=shift(zoo::rollapply(`New Cases`,7,mean),0),
                               NewCasesMA_c:=zoo::rollapply(`New Cases`,7,mean),
                               SelectedRegion]

confirmed_cases_long_bycountry[order(case_date),
                               #NewCasesMA:=shift(zoo::rollapply(`New Cases`,7,mean),0),
                               NewCasesMA:=shift(NewCasesMA_c,6),
                               SelectedRegion]

#View(confirmed_cases_long_bycountry[SelectedRegion=="New Zealand"])
```


```{r}

new_cases<-confirmed_cases_long_bycountry[!is.na(NewCasesMA)]

# if(threshold<min(new_cases[SelectedRegion=="Mainland China",`Confirmed Cases`])){
#        new_cases <-
#          new_cases[SelectedRegion!="Mainland China"]
#      }

case_limit<-40
days_limit <- 21

#now we want a list of the lines
#with an x axis point either at the end of the graph,
#or at the end of the line, whichever is first,     
country_labels<-new_cases[,
                              .(intercept_date=max(case_date)),
                              by=SelectedRegion] %>% 
 merge(new_cases[,.(SelectedRegion,case_date,NewCasesMA)],
                     by.x=c("SelectedRegion","intercept_date"),
                     by.y=c("SelectedRegion","case_date"),
       all.x=TRUE,all.y=FALSE)

country_labels[,NewCasesGroup:=round(log(NewCasesMA,10),1)]
country_labels_grouped<- country_labels[,
                                        .(Countries=paste0(SelectedRegion, collapse=", "),
                                          GroupedNewCases=mean(NewCasesMA),
                                          SelectedRegion = .SD[,SelectedRegion][[1]]
                                          )
                                        ,by=.(NewCasesGroup,intercept_date)] %>% .[GroupedNewCases>2]
x_breaks  <- seq(min(new_cases$case_date),max(new_cases$case_date),7)



myplot<-ggplot(new_cases
      ,
      aes(x=as.Date(case_date),y=NewCasesMA,
          group=SelectedRegion))+
 geom_line(size=1,alpha=0.3)+
  theme_classic()+
 #geom_point(alpha=0.5)+
 scale_x_date(#breaks=x_breaks,
   date_breaks = "7 days",
                    minor_breaks=NULL,date_labels="%b %d")+
 coord_cartesian(xlim=c(min(new_cases$case_date),max(new_cases$case_date)+7),
                 ylim=c(10,max(new_cases$NewCasesMA)))+
 scale_y_continuous(trans = "log10",
                    breaks = c(2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000),
                    minor_breaks=NULL,
                    labels = scales::comma,
                    sec.axis = dup_axis())+
 #geom_vline(xintercept = 0,linetype="dashed")+
 #geom_hline(yintercept = threshold,,linetype="dashed")+
 labs(title=paste0("New confirmed cases by day and country"),
      x=paste0("Date"),
      y="New Cases (7 day rolling average)",
      color="Date Country Reached Threshold",
      caption="Source: John Hopkins Dataset")+
 theme(legend.position = "none")+
 geom_text(data=country_labels_grouped,
           aes(x=intercept_date,y=GroupedNewCases,label=Countries),
           hjust=0,size=2,fontface="bold")


htmlwidgets::saveWidget(as_widget(ggplotly(myplot)),"new_cases.html",selfcontained=FALSE)
  
myplot
```
```{r}

new_cases<-confirmed_cases_long_bycountry[!is.na(NewCasesMA)]

# if(threshold<min(new_cases[SelectedRegion=="Mainland China",`Confirmed Cases`])){
#        new_cases <-
#          new_cases[SelectedRegion!="Mainland China"]
#      }

case_limit<-40
days_limit <- 21

#now we want a list of the lines
#with an x axis point either at the end of the graph,
#or at the end of the line, whichever is first,     
country_labels<-new_cases[,
                              .(intercept_date=max(case_date)),
                              by=SelectedRegion] %>% 
 merge(new_cases[,.(SelectedRegion,case_date,NewCasesMA)],
                     by.x=c("SelectedRegion","intercept_date"),
                     by.y=c("SelectedRegion","case_date"),
       all.x=TRUE,all.y=FALSE)

country_labels[,NewCasesGroup:=round(log(NewCasesMA,10),2)]
country_labels_grouped<- country_labels[,
                                        .(Countries=paste0(SelectedRegion, collapse=", "),
                                          GroupedNewCases=mean(NewCasesMA),
                                          SelectedRegion = .SD[,SelectedRegion][[1]]
                                          )
                                        ,by=.(NewCasesGroup,intercept_date)] %>% .[GroupedNewCases>2]
x_breaks  <- seq(min(new_cases$case_date),max(new_cases$case_date),7)



myplot<-ggplot(new_cases
      ,
      aes(x=as.Date(case_date),y=NewCasesMA,color=SelectedRegion,
          group=SelectedRegion))+
 geom_line(size=1,alpha=0.5)+
  theme_classic()+
 #geom_point(alpha=0.5)+
 scale_x_date(#breaks=x_breaks,
   date_breaks = "7 days",
                    minor_breaks=NULL,date_labels="%b %d")+
 coord_cartesian(xlim=c(max(new_cases$case_date)-21,max(new_cases$case_date)+3),
                 ylim=c(20,max(new_cases$NewCasesMA)))+
 scale_y_continuous(trans = "log10",
                    breaks = c(2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000),
                    minor_breaks=NULL,
                    labels = scales::comma,
                    sec.axis = dup_axis())+
 #geom_vline(xintercept = 0,linetype="dashed")+
 #geom_hline(yintercept = threshold,,linetype="dashed")+
 labs(title=paste0("New confirmed cases by day and country"),
      x=paste0("Date"),
      y="New Cases (7 day rolling average)",
      color="Date Country Reached Threshold",
      caption="Source: John Hopkins Dataset")+
 theme(legend.position = "none")+
 geom_text(data=country_labels_grouped[!(Countries %in% c("Switzerland","Norway"))],
           aes(x=intercept_date,y=GroupedNewCases,label=Countries),
           hjust=0,size=2,fontface="bold")


htmlwidgets::saveWidget(as_widget(ggplotly(myplot)),"new_cases.html",selfcontained=FALSE)
  
myplot
```



